# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 653aa026809cc40596828d728b8c80c8077fbcaf33e27226deb7a286c49f8b9245567930d4f4321e69eb1792b0a5b26d45261b858daa5558c0ba91eab811f909

test:
  secret_key_base: 7d09e95e5b7f56c3f09ef8704eef0208ebad176fb9f85179391d3eb88c2d785d88d6dac5d212664829c4a7bf426d0e591b7c3371385e62c4b6b9cb18df3ee79a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
